### ISSUE TITLE
Implement voice input for search and chat

### ISSUE THREAD

**Issue by areebahmeddd** [SpaceTesla/Mivro#114]
We have input box in main screen and chat screen, enable voice input for chat screen since it's working now

Input box on chat screen is still being worked on by @rishichirchi
Related to Issue #113

**Comment by suyashutekar11** [comment]
**Add Dependencies**
`dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^4.2.0
  flutter_tts: ^3.4.0  # Optional, for text-to-speech feedback
`

**Run flutter pub get to install the dependencies.**
`flutter pub get
`
-----------------------------------------------------------
**Import the necessary packages in your Dart file:**
`import 'package:flutter/material.dart';
import 'package:speech_to_text/speech_to_text.dart' as stt;
import 'package:flutter_tts/flutter_tts.dart';`


--------------------------------------------------------------------
**Initialize the SpeechToText and FlutterTts objects:**
`class VoiceSearchChat extends StatefulWidget {
  @override
  _VoiceSearchChatState createState() => _VoiceSearchChatState();
}

class _VoiceSearchChatState extends State<VoiceSearchChat> {
  stt.SpeechToText _speech;
  bool _isListening = false;
  String _text = "Press the button to start speaking";
  FlutterTts _flutterTts;

  @override
  void initState() {
    super.initState();
    _speech = stt.SpeechToText();
    _flutterTts = FlutterTts(); // Optional
  }
`

---------------------------------------------------------------------
**Method to listen user voice:**
`void _startListening() async {
  bool available = await _speech.initialize(
    onStatus: (val) => print('onStatus: $val'),
    onError: (val) => print('onError: $val'),
  );
  if (available) {
    setState(() => _isListening = true);
    _speech.listen(
      onResult: (val) => setState(() {
        _text = val.recognizedWords;
        if (val.hasConfidenceRating && val.confidence > 0) {
          _text = '${val.recognizedWords}';
        }
      }),
    );
  } else {
    setState(() => _isListening = false);
    _speech.stop();
  }
}

void _stopListening() {
  setState(() => _isListening = false);
  _speech.stop();
}
`
-------------------------------------------------------------
 **UI with a button to start/stop voice input and display the recognized text:**
@override
Widget build(BuildContext context) {
  return Scaffold(
    appBar: AppBar(
      title: Text("Voice Search & Chat"),
    ),
    body: Column(
      children: [
        Expanded(
          child: Container(
            padding: const EdgeInsets.all(16.0),
            child: Text(
              _text,
              style: TextStyle(fontSize: 24.0),
            ),
          ),
        ),
        FloatingActionButton(
          onPressed: _isListening ? _stopListening : _startListening,
          child: Icon(_isListening ? Icons.mic : Icons.mic_none),
        ),
      ],
    ),
  );
}
----------------------------------------------------------------------
**Add the necessary permissions in your AndroidManifest.xml (for Android)** 
xml:
`<uses-permission android:name="android.permission.RECORD_AUDIO"/>
`

**Comment by suyashutekar11** [comment]
[Solution .txt](https://github.com/user-attachments/files/16550332/Solution.txt)
